

INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (1, 'dw_hos', 1, 10, 0, 'wuhongming', 1543819148601, 'wuhongming', 1543819148602, NULL, 1, NULL, 1543919816338, 1543920573969, 0, 'orcl', 1, 4669, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (2, 'kettle(FULL5)', 1, 10, 1, 'wuhongming', 1543819352943, 'fang', 1543919814558, '', 1, NULL, 1543973772773, NULL, 0, 'orcl', 1, 6, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (3, 'ypxt', 2, 10, 0, 'wuhongming', 1543820649808, 'wuhongming', 1543820649808, NULL, 1, NULL, 1543973754262, 1543974389350, 0, 'orcl', 1, 2684, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (4, 'xtgl', 3, 10, 0, 'wuhongming', 1543820898283, 'wuhongming', 1543820898283, NULL, 1, NULL, 1543821372957, 1543821804275, 0, 'orcl', 1, 1789, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (5, 'bqxt', 4, 10, 0, 'wuhongming', 1543822694364, 'wuhongming', 1543822694364, NULL, 1, NULL, 1543888236470, NULL, 0, 'orcl', 1, 5556, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (6, 'kettle(ft)', 2, 10, 1, 'wuhongming', 1543822814258, 'fang', 1543917561415, '', -1, NULL, 1543974681090, 1543830355784, 0, 'orcl', 1, 0, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (7, 'kettle(buquan)', 3, 10, 1, 'wuhongming', 1543825391456, 'fang', 1543974834106, '', 1, '13364', 1543974836908, NULL, 0, 'orcl', 1, 6, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (8, 'mzxt', 5, 10, 0, 'wuhongming', 1543829024680, 'wuhongming', 1543829024680, NULL, 1, NULL, 1543829027628, NULL, 0, 'orcl', 1, 2814, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (9, 'whmtest', 6, 10, 0, 'wuhongming', 1543892234841, 'wuhongming', 1543892234841, NULL, 1, '9504', 1544060976667, NULL, 2, 'whmtest', 1, 143, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (10, 'whm12', 7, 10, 0, 'wuhongming', 1543892320863, 'wuhongming', 1543892320863, 'Traceback (most recent call last):\n  File \"src/pymssql.pyx\", line 636, in pymssql.connect\n  File \"src/_mssql.pyx\", line 1957, in _mssql.connect\n  File \"src/_mssql.pyx\", line 676, in _mssql.MSSQLConnection.__init__\n  File \"src/_mssql.pyx\", line 1683, in _mssql.maybe_raise_MSSQLDatabaseException\n_mssql.MSSQLDatabaseException: (20009, b\'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (192.168.202.13:1433)\\nNet-Lib error during Connection refused (111)\\n\')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2158, in _wrap_pool_connect\n    return fn()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 400, in connect\n    return _ConnectionFairy._checkout(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 788, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 529, in checkout\n    rec = pool._do_get()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 1193, in _do_get\n    self._dec_overflow()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py\", line 66, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 249, in reraise\n    raise value\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 1190, in _do_get\n    return self._create_connection()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 347, in _create_connection\n    return _ConnectionRecord(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 474, in __init__\n    self.__connect(first_connect_check=True)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 671, in __connect\n    connection = pool._invoke_creator(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 106, in connect\n    return dialect.connect(*cargs, **cparams)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py\", line 412, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n  File \"src/pymssql.pyx\", line 642, in pymssql.connect\npymssql.OperationalError: (20009, b\'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (192.168.202.13:1433)\\nNet-Lib error during Connection refused (111)\\n\')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/discover_data/sourcedata-py/main1.py\", line 142, in main\n    metadata.main()\n  File \"/discover_data/sourcedata-py/metadata/metadata.py\", line 881, in main\n    uu = self.message()\n  File \"/discover_data/sourcedata-py/metadata/metadata.py\", line 490, in message\n    v = str(pd.read_sql(sql,self.db).loc[0,\'name\'])\n  File \"/usr/local/lib/python3.6/site-packages/pandas/io/sql.py\", line 397, in read_sql\n    chunksize=chunksize)\n  File \"/usr/local/lib/python3.6/site-packages/pandas/io/sql.py\", line 1063, in read_query\n    result = self.execute(*args)\n  File \"/usr/local/lib/python3.6/site-packages/pandas/io/sql.py\", line 954, in execute\n    return self.connectable.execute(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2074, in execute\n    connection = self.contextual_connect(close_with_result=True)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2123, in contextual_connect\n    self._wrap_pool_connect(self.pool.connect, None),\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2162, in _wrap_pool_connect\n    e, dialect, self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1476, in _handle_dbapi_exception_noconnection\n    exc_info\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 265, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 248, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2158, in _wrap_pool_connect\n    return fn()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 400, in connect\n    return _ConnectionFairy._checkout(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 788, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 529, in checkout\n    rec = pool._do_get()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 1193, in _do_get\n    self._dec_overflow()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py\", line 66, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 249, in reraise\n    raise value\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 1190, in _do_get\n    return self._create_connection()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 347, in _create_connection\n    return _ConnectionRecord(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 474, in __init__\n    self.__connect(first_connect_check=True)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 671, in __connect\n    connection = pool._invoke_creator(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 106, in connect\n    return dialect.connect(*cargs, **cparams)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py\", line 412, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n  File \"src/pymssql.pyx\", line 642, in pymssql.connect\nsqlalchemy.exc.OperationalError: (pymssql.OperationalError) (20009, b\'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (192.168.202.13:1433)\\nNet-Lib error during Connection refused (111)\\n\') (Background on this error at: http://sqlalche.me/e/e3q8)\n', 2, '90547', 1543978820835, 1543978822815, 1, 'whm12', 1, 0, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (11, '196.168.202.2', 8, 20, 0, 'wuhongming', 1543907040297, 'wuhongming', 1543907040297, NULL, 1, '4056', 1544060565346, 1544060868931, 0, 'orcl', 1, 713, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (12, 'whm1234', 9, 10, 0, 'wuhongming', 1543908226254, 'wuhongming', 1543908226254, NULL, 0, NULL, 1544063968331, NULL, 2, 'whm1234', 1, 43, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (13, 'xvf', 4, 5, 1, 'wuhongming', 1543908582339, 'wuhongming', 1543908582339, NULL, -1, NULL, 1543908669434, NULL, 0, 'orcl', 1, 0, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (14, 'wer3', 5, 5, 1, 'wuhongming', 1543909033245, 'wuhongming', 1543909033245, NULL, -1, NULL, 1543909039680, NULL, 0, 'orcl', 1, 0, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (15, 'wer5', 6, 5, 1, 'wuhongming', 1543909277346, 'wuhongming', 1543909277346, NULL, -1, NULL, NULL, NULL, 0, 'orcl', 1, 0, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (16, 'errr', 7, 10, 1, 'fang', 1543915075167, 'fang', 1543915075167, NULL, -1, NULL, 1543915557365, NULL, 0, 'orcl', 1, 0, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (17, 'sdfddfg', 8, 10, 1, 'wuhongming', 1543915191158, 'wuhongming', 1543915191158, NULL, -1, NULL, NULL, NULL, 0, 'orcl', 1, 0, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (18, 'sdfddfg1', 9, 10, 1, 'wuhongming', 1543915237788, 'wuhongming', 1543915237788, NULL, -1, NULL, NULL, NULL, 0, 'orcl', 1, 0, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (19, 'whm111', 10, 10, 0, 'wuhongming', 1543979394349, 'wuhongming', 1543979394349, 'Traceback (most recent call last):\n  File \"src/pymssql.pyx\", line 636, in pymssql.connect\n  File \"src/_mssql.pyx\", line 1957, in _mssql.connect\n  File \"src/_mssql.pyx\", line 676, in _mssql.MSSQLConnection.__init__\n  File \"src/_mssql.pyx\", line 1683, in _mssql.maybe_raise_MSSQLDatabaseException\n_mssql.MSSQLDatabaseException: (20009, b\'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (192.168.202.13:1433)\\nNet-Lib error during Connection refused (111)\\n\')\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2158, in _wrap_pool_connect\n    return fn()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 400, in connect\n    return _ConnectionFairy._checkout(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 788, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 529, in checkout\n    rec = pool._do_get()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 1193, in _do_get\n    self._dec_overflow()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py\", line 66, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 249, in reraise\n    raise value\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 1190, in _do_get\n    return self._create_connection()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 347, in _create_connection\n    return _ConnectionRecord(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 474, in __init__\n    self.__connect(first_connect_check=True)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 671, in __connect\n    connection = pool._invoke_creator(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 106, in connect\n    return dialect.connect(*cargs, **cparams)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py\", line 412, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n  File \"src/pymssql.pyx\", line 642, in pymssql.connect\npymssql.OperationalError: (20009, b\'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (192.168.202.13:1433)\\nNet-Lib error during Connection refused (111)\\n\')\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/discover_data/sourcedata-py/main1.py\", line 142, in main\n    metadata.main()\n  File \"/discover_data/sourcedata-py/metadata/metadata.py\", line 881, in main\n    uu = self.message()\n  File \"/discover_data/sourcedata-py/metadata/metadata.py\", line 490, in message\n    v = str(pd.read_sql(sql,self.db).loc[0,\'name\'])\n  File \"/usr/local/lib/python3.6/site-packages/pandas/io/sql.py\", line 397, in read_sql\n    chunksize=chunksize)\n  File \"/usr/local/lib/python3.6/site-packages/pandas/io/sql.py\", line 1063, in read_query\n    result = self.execute(*args)\n  File \"/usr/local/lib/python3.6/site-packages/pandas/io/sql.py\", line 954, in execute\n    return self.connectable.execute(*args, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2074, in execute\n    connection = self.contextual_connect(close_with_result=True)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2123, in contextual_connect\n    self._wrap_pool_connect(self.pool.connect, None),\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2162, in _wrap_pool_connect\n    e, dialect, self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1476, in _handle_dbapi_exception_noconnection\n    exc_info\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 265, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 248, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2158, in _wrap_pool_connect\n    return fn()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 400, in connect\n    return _ConnectionFairy._checkout(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 788, in _checkout\n    fairy = _ConnectionRecord.checkout(pool)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 529, in checkout\n    rec = pool._do_get()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 1193, in _do_get\n    self._dec_overflow()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py\", line 66, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 249, in reraise\n    raise value\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 1190, in _do_get\n    return self._create_connection()\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 347, in _create_connection\n    return _ConnectionRecord(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 474, in __init__\n    self.__connect(first_connect_check=True)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/pool.py\", line 671, in __connect\n    connection = pool._invoke_creator(self)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py\", line 106, in connect\n    return dialect.connect(*cargs, **cparams)\n  File \"/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py\", line 412, in connect\n    return self.dbapi.connect(*cargs, **cparams)\n  File \"src/pymssql.pyx\", line 642, in pymssql.connect\nsqlalchemy.exc.OperationalError: (pymssql.OperationalError) (20009, b\'DB-Lib error message 20009, severity 9:\\nUnable to connect: Adaptive Server is unavailable or does not exist (192.168.202.13:1433)\\nNet-Lib error during Connection refused (111)\\n\') (Background on this error at: http://sqlalche.me/e/e3q8)\n', -1, '92091', 1543979699298, NULL, 1, 'whm111', 1, 10, 0, NULL);
INSERT INTO `data_manager`.`collect_job`(`id`, `job_name`, `source_id`, `sample_line`, `collect_type`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`, `status`, `thread_id`, `start_time`, `end_time`, `db_type`, `db_name`, `version`, `count_all`, `count_err`, `file_path`) VALUES (20, 'whm13', 11, 10, 0, 'wuhongming', 1543996632458, 'wuhongming', 1543996632458, NULL, 1, NULL, 1544003731535, NULL, 1, 'whm13', 1, 31, 0, NULL);





INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (1, 'dw_hos', 0, '192.168.226.27', '1521', 'DW_HOS', 'dw_hos', 'orcl', NULL, 'table,view', 'wuhongming', 1543819148424, 'wuhongming', 1543819148429, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (2, 'ypxt', 0, '192.168.226.27', '1521', 'YPXT', 'oracle', 'orcl', NULL, 'table,view', 'wuhongming', 1543820649780, 'wuhongming', 1543820649780, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (3, 'xtgl', 0, '192.168.226.27', '1521', 'XTGL', 'oracle', 'orcl', NULL, 'table,view', 'wuhongming', 1543820898252, 'wuhongming', 1543820898252, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (4, 'bqxt', 0, '192.168.226.27', '1521', 'BQXT', 'oracle', 'orcl', NULL, 'table,view', 'wuhongming', 1543822694326, 'wuhongming', 1543822694327, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (5, 'mzxt', 0, '192.168.226.27', '1521', 'MZXT', 'oracle', 'orcl', NULL, 'table', 'wuhongming', 1543829024509, 'wuhongming', 1543829024509, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (6, 'whmtest', 2, '192.168.240.201', '3306', 'root', 'Hzmc321#', 'whmtest', NULL, 'table,view', 'wuhongming', 1543892234782, 'wuhongming', 1543892234782, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (7, 'whm12', 1, '192.168.202.13', '1433', 'sa', 'hzmc321#', 'whm12', NULL, 'table,view', 'wuhongming', 1543892320856, 'wuhongming', 1543892320856, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (8, '196.168.202.2', 0, '192.168.202.2', '1521', 'SH', 'sh', 'orcl', NULL, 'table,view', 'wuhongming', 1543907040251, 'wuhongming', 1543907040252, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (9, 'whm1234', 2, '192.168.240.201', '3306', 'root', 'Hzmc321#', 'whm1234', NULL, 'table,view', 'wuhongming', 1543908226249, 'wuhongming', 1543908226249, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (10, 'whm111', 1, '192.168.202.13', '1433', 'sa', 'hzmc321#', 'whm111', NULL, 'table', 'wuhongming', 1543979394344, 'wuhongming', 1543979394344, NULL);
INSERT INTO `data_manager`.`db_config`(`id`, `config_name`, `config_type`, `host`, `port`, `username`, `password`, `db_name`, `schema_name`, `conn_props`, `create_by`, `create_at`, `update_by`, `update_at`, `remark`) VALUES (11, 'whm13', 1, '192.168.202.13', '1433', 'sa', 'hzmc321#', 'whm13', NULL, 'table,view', 'wuhongming', 1543996632436, 'wuhongming', 1543996632436, NULL);




INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (1, 1, 'kettle(FULL5)', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"deploy\",\"kettle\"],\"kettle\":[\"3@53\",\"3@54\",\"3@55\",\"3@56\",\"3@57\",\"3@58\"]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.240.154', 'root', 'root', NULL, NULL, 'wuhongming', 1543819352898, 'fang', 1543919814555);
INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (2, 1, 'kettle(ft)', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"deploy\",\"kettle\"],\"kettle\":[\"3@47\",\"3@48\",\"3@52\"]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.240.154', 'root', 'root', NULL, NULL, 'wuhongming', 1543822814229, 'fang', 1543917561412);
INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (3, 1, 'kettle(buquan)', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"deploy\",\"kettle\"],\"kettle\":[\"3@29\",\"3@30\",\"3@31\",\"3@32\",\"3@33\",\"3@34\"]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.240.154', 'root', 'root', NULL, NULL, 'wuhongming', 1543825391437, 'fang', 1543974834104);
INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (4, 1, 'xvf', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"deploy\"],\"kettle\":[]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.2.4', 'root', 'root', NULL, NULL, 'wuhongming', 1543908582302, 'wuhongming', 1543908582302);
INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (5, 1, 'wer3', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"deploy\"],\"kettle\":[]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.2.34', 'root', 'root', NULL, NULL, 'wuhongming', 1543909033238, 'wuhongming', 1543909033238);
INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (6, 1, 'wer5', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"deploy\"],\"kettle\":[]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.2.34', 'root', 'root', NULL, NULL, 'wuhongming', 1543909277341, 'wuhongming', 1543909277341);
INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (7, 1, '23444', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"kettle\"],\"kettle\":[\"3@29\",\"3@30\",\"3@31\",\"3@32\",\"2@21\",\"3@33\",\"3@34\",\"3@131\",\"3@129\",\"2@3\",\"3@3\",\"3@2\",\"3@4\",\"3@6\",\"3@7\",\"3@5\",\"3@130\"]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.240.154', 'root', 'root', NULL, NULL, 'fang', 1543915075159, 'fang', 1543915075159);
INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (8, 1, 'sdfddfg', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"deploy\"],\"kettle\":[]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.240.154', 'root', 'root', NULL, NULL, 'wuhongming', 1543915191129, 'wuhongming', 1543915191129);
INSERT INTO `data_manager`.`etl_config`(`id`, `is_repo`, `etl_name`, `etl_user`, `etl_pass`, `conn_type`, `conn_way`, `conn_props`, `db_host`, `db_port`, `db_name`, `db_user`, `db_pass`, `os_host`, `os_user`, `os_pass`, `file_path`, `kettle_path`, `create_by`, `create_at`, `update_by`, `update_at`) VALUES (9, 1, 'sdfddfg1', 'admin', 'admin', 0, 0, '{\"commons\":[\"server\",\"deploy\",\"kettle\"],\"kettle\":[\"3@53\",\"3@54\",\"3@55\",\"3@56\",\"3@57\",\"3@58\",\"3@59\",\"3@60\",\"3@61\",\"3@62\",\"3@63\",\"3@64\",\"3@65\",\"3@66\",\"3@67\",\"3@68\",\"3@69\",\"3@70\",\"3@71\",\"3@72\",\"3@73\",\"3@74\",\"3@75\",\"3@76\",\"3@77\",\"3@78\",\"3@79\",\"3@80\",\"3@81\",\"3@82\",\"3@83\",\"3@84\",\"3@85\",\"3@86\",\"3@87\",\"3@88\",\"3@89\",\"3@91\",\"3@90\",\"3@92\",\"3@93\",\"3@94\",\"3@95\",\"3@96\",\"3@97\",\"3@98\",\"3@99\",\"3@100\",\"3@101\",\"3@102\",\"3@103\",\"3@104\",\"3@105\",\"3@106\",\"3@107\",\"3@108\",\"3@109\",\"3@110\",\"3@111\",\"3@112\",\"3@113\",\"3@114\",\"3@115\",\"3@116\",\"3@117\",\"3@118\",\"3@119\",\"3@120\",\"3@121\",\"3@122\"]}', '192.168.202.2', '1521', 'orcl', 'sh', 'sh', '192.168.240.154', 'root', 'root', NULL, NULL, 'wuhongming', 1543915237779, 'wuhongming', 1543915237779);
